"""
strategy/base.py
────────────────
Abstract Strategy interface and fundamental Signal models.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Literal

from core.models import Candle


SignalSide = Literal["BUY", "SELL"]


@dataclass(frozen=True, slots=True)
class Signal:
    """Represents a discrete trading signal generated by the strategy engine."""
    side: SignalSide
    timestamp: int
    price: float
    reason: str


class BaseStrategy(ABC):
    """
    Contract for all trading strategies.
    
    Any strategy (e.g. SMMA Cross, RSI Reversion) must inherit from this
    class and implement the generate_signal method. This ensures that the
    engine (backtest/live) can swap strategies without changing its logic.
    """

    @abstractmethod
    def generate_signal(self, historical_candles: list[Candle]) -> Signal | None:
        """
        Evaluate historical market data and return a trading signal if valid.
        
        Args:
            historical_candles: A list of confirmed/closed Candle objects.
            
        Returns:
            A Signal object if a trade condition is met, otherwise None.
        """
        pass
